"use client";

import { Clock3, ExternalLink, LogIn, LogOut, MapPinOff, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

import { GeofenceMap, formatCoordinates, formatDistance } from "@/components/GeofenceMap";
import { Button, EmptyState, Spinner } from "@/components/ui";
import {
  ApiError,
  type Geofence,
  type GeofenceEvent,
  type LocationReport,
  getLatestLocation,
  listGeofenceEvents,
  listGeofences,
} from "@/lib/apiClient";

import styles from "./DeviceLocationPanel.module.css";

type LocationState =
  | { kind: "loading" }
  | { kind: "loaded"; report: LocationReport | null; loadedAt: number }
  | { kind: "error"; message: string };

type ZonesState = { kind: "loading" } | { kind: "loaded"; geofences: Geofence[] } | { kind: "error" };

type MovesState = { kind: "loading" } | { kind: "loaded"; events: GeofenceEvent[] } | { kind: "error" };

const GOOGLE_MAPS_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
const EARTH_RADIUS_METERS = 6_371_008.8;
const RECENT_MOVES = 5;

function describeError(error: unknown, fallback: string): string {
  return error instanceof ApiError ? error.message : fallback;
}

function formatCapturedAt(value: string): string {
  return new Date(value).toLocaleString("es-CO", { dateStyle: "medium", timeStyle: "short" });
}

/** "hace N min", measured against the moment the reading arrived (not a ticking clock). */
function formatAge(milliseconds: number): string {
  const minutes = Math.max(0, Math.floor(milliseconds / 60_000));
  if (minutes < 1) return "hace menos de 1 min";
  if (minutes < 60) return `hace ${minutes} min`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return minutes % 60 === 0 ? `hace ${hours} h` : `hace ${hours} h ${minutes % 60} min`;
  const days = Math.floor(hours / 24);
  return days === 1 ? "hace 1 día" : `hace ${days} días`;
}

/** Haversine: the same great-circle distance the backend uses to detect entries and exits. */
function distanceMeters(aLat: number, aLon: number, bLat: number, bLon: number): number {
  const toRad = (degrees: number) => (degrees * Math.PI) / 180;
  const dLat = toRad(bLat - aLat);
  const dLon = toRad(bLon - aLon);
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(aLat)) * Math.cos(toRad(bLat)) * Math.sin(dLon / 2) ** 2;
  return 2 * EARTH_RADIUS_METERS * Math.asin(Math.min(1, Math.sqrt(h)));
}

function formatMoveTime(iso: string): string {
  return new Date(iso).toLocaleString("es-CO", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" });
}

/** Sprint 13 (logic), Sprint 57 (tracking composition). Renders a real embedded map only when
 * NEXT_PUBLIC_GOOGLE_MAPS_API_KEY is configured — that key can't be generated by an agent (it
 * needs a Google Cloud account and an HTTP-referrer restriction, see docs/sprint-13.md). Without
 * it, the panel draws the same hand-made schematic as Geocercas plus a plain link to Google Maps.
 * Every read of the latest location is audited server-side (LOCATION_VIEWED, Sprint 47), so this
 * panel reads it exactly once per mount and once per "Actualizar" — no polling. The containing
 * zone is computed here from the geofences already configured; there is no street address (the
 * backend has no geocoding, docs/redesign/fase-0-informe.md §5). */
export function DeviceLocationPanel({
  accessToken,
  deviceId,
}: {
  accessToken: string;
  deviceId: string;
}) {
  const [state, setState] = useState<LocationState>({ kind: "loading" });
  const [zonesState, setZonesState] = useState<ZonesState>({ kind: "loading" });
  const [movesState, setMovesState] = useState<MovesState>({ kind: "loading" });
  const [reloadToken, setReloadToken] = useState(0);

  useEffect(() => {
    let cancelled = false;

    getLatestLocation(accessToken, deviceId)
      .then(({ report }) => {
        if (!cancelled) {
          setState({ kind: "loaded", report, loadedAt: Date.now() });
        }
      })
      .catch((error) => {
        if (!cancelled) {
          setState({ kind: "error", message: describeError(error, "No se pudo cargar la ubicación") });
        }
      });

    return () => {
      cancelled = true;
    };
  }, [accessToken, deviceId, reloadToken]);

  // Zones (not audited) to name the one the device is in and to draw them on the schematic.
  useEffect(() => {
    let cancelled = false;

    listGeofences(accessToken, deviceId)
      .then(({ geofences }) => {
        if (!cancelled) {
          setZonesState({ kind: "loaded", geofences });
        }
      })
      .catch(() => {
        if (!cancelled) {
          setZonesState({ kind: "error" });
        }
      });

    return () => {
      cancelled = true;
    };
  }, [accessToken, deviceId, reloadToken]);

  // The latest entries/exits (not audited): the movement history under the reading.
  useEffect(() => {
    let cancelled = false;

    listGeofenceEvents(accessToken, deviceId)
      .then(({ events }) => {
        if (!cancelled) {
          setMovesState({ kind: "loaded", events });
        }
      })
      .catch(() => {
        if (!cancelled) {
          setMovesState({ kind: "error" });
        }
      });

    return () => {
      cancelled = true;
    };
  }, [accessToken, deviceId, reloadToken]);

  const reload = useCallback(() => {
    setState({ kind: "loading" });
    setZonesState({ kind: "loading" });
    setMovesState({ kind: "loading" });
    setReloadToken((current) => current + 1);
  }, []);

  const report = state.kind === "loaded" ? state.report : null;
  const geofences = useMemo(() => (zonesState.kind === "loaded" ? zonesState.geofences : []), [zonesState]);

  const containing = useMemo(() => {
    if (!report) return null;
    const inside = geofences
      .map((geofence) => ({
        geofence,
        distance: distanceMeters(report.latitude, report.longitude, geofence.latitude, geofence.longitude),
      }))
      .filter(({ geofence, distance }) => distance <= geofence.radius_meters)
      .sort((a, b) => a.geofence.radius_meters - b.geofence.radius_meters);
    return inside[0] ?? null;
  }, [report, geofences]);

  const recentMoves = useMemo(
    () =>
      movesState.kind === "loaded"
        ? [...movesState.events]
            .sort((a, b) => Date.parse(b.occurred_at) - Date.parse(a.occurred_at))
            .slice(0, RECENT_MOVES)
        : [],
    [movesState]
  );

  let placeTitle = "Última ubicación conocida";
  let placeDetail = "";
  if (report && zonesState.kind === "loaded") {
    if (containing) {
      placeTitle = containing.geofence.name;
      placeDetail = `Dentro del radio de ${formatDistance(containing.geofence.radius_meters)}, a ${formatDistance(containing.distance)} del centro.`;
    } else if (geofences.length === 0) {
      placeDetail = "No hay geocercas configuradas para nombrar este lugar.";
    } else {
      placeTitle = "Fuera de zonas conocidas";
      placeDetail = `No está dentro de ninguna de tus ${geofences.length === 1 ? "geocerca" : `${geofences.length} geocercas`}.`;
    }
  } else if (report && zonesState.kind === "error") {
    placeDetail = "No se pudieron cargar las geocercas para nombrar este lugar.";
  }

  const refreshing = state.kind === "loading";

  return (
    <>
      {state.kind === "error" && (
        <section className={styles.notice}>
          <p className={styles.error} role="alert">
            {state.message}
          </p>
          <Button size="sm" icon={RefreshCw} onClick={reload}>
            Reintentar
          </Button>
        </section>
      )}

      {state.kind === "loading" && (
        <section className={styles.notice}>
          <Spinner label="Cargando ubicación…" />
        </section>
      )}

      {state.kind === "loaded" && report === null && (
        <section className={styles.notice}>
          <EmptyState
            icon={MapPinOff}
            illustration={
              <span className={styles.emptyArt} aria-hidden="true">
                <span className={styles.emptyRing} />
                <MapPinOff size={24} strokeWidth={1.75} className={styles.emptyIcon} />
              </span>
            }
            title="Todavía no hay ubicación reciente de este dispositivo"
            description="El dispositivo informa su posición cada ~15 minutos cuando tiene concedido el permiso de ubicación. Aquí aparecerá la última que envíe."
            action={
              <Button size="sm" icon={RefreshCw} onClick={reload}>
                Actualizar
              </Button>
            }
          />
        </section>
      )}

      {state.kind === "loaded" && report && (
        <section className={styles.tracker} aria-label="Ubicación actual">
          <div className={styles.reading}>
            <p className={`eyebrow ${styles.eyebrow}`}>Ubicación actual</p>
            <h2 className={styles.place}>{placeTitle}</h2>
            {placeDetail && <p className={styles.placeDetail}>{placeDetail}</p>}
            <p className={styles.age}>
              <Clock3 size={15} strokeWidth={2} aria-hidden="true" />
              <span>
                Reportada <strong>{formatAge(state.loadedAt - Date.parse(report.captured_at))}</strong>
              </span>
            </p>
          </div>

          <div className={styles.mapArea}>
            {GOOGLE_MAPS_API_KEY ? (
              <iframe
                className={styles.map}
                title="Última ubicación conocida"
                loading="lazy"
                referrerPolicy="no-referrer-when-downgrade"
                src={`https://www.google.com/maps/embed/v1/view?key=${GOOGLE_MAPS_API_KEY}&center=${report.latitude},${report.longitude}&zoom=14`}
              />
            ) : (
              <GeofenceMap
                geofences={geofences}
                location={report}
                activeId={containing?.geofence.id ?? null}
                variant="tracking"
              />
            )}
          </div>

          <div className={styles.details}>
            <dl className={styles.facts}>
              <div className={styles.fact}>
                <dt>Coordenadas</dt>
                <dd className={styles.figure}>
                  {formatCoordinates(report.latitude, report.longitude)}
                </dd>
              </div>
              <div className={styles.fact}>
                <dt>Precisión aproximada</dt>
                <dd className={styles.figure}>±{Math.round(report.accuracy_meters).toLocaleString("es-CO")} m</dd>
              </div>
              <div className={styles.fact}>
                <dt>Capturada</dt>
                <dd>{formatCapturedAt(report.captured_at)}</dd>
              </div>
            </dl>

            <p className={styles.cadence}>
              El dispositivo informa su posición cada ~15 minutos: lo que ves puede tener ese retraso, no es
              seguimiento en tiempo real.
            </p>

            <div className={styles.actions}>
              <Button icon={RefreshCw} onClick={reload} loading={refreshing}>
                Actualizar
              </Button>
              <a
                className={styles.mapLink}
                href={`https://www.google.com/maps?q=${report.latitude},${report.longitude}`}
                target="_blank"
                rel="noreferrer"
              >
                Abrir en Google Maps <ExternalLink size={14} aria-hidden="true" />
              </a>
            </div>

            {!GOOGLE_MAPS_API_KEY && (
              <p className={styles.footnote}>
                El mapa embebido necesita la clave <code>NEXT_PUBLIC_GOOGLE_MAPS_API_KEY</code>, que genera una persona
                con cuenta de Google Cloud; mientras tanto se muestra el esquema propio.
              </p>
            )}
          </div>
        </section>
      )}

      {state.kind === "loaded" && (
        <section className={styles.moves} aria-labelledby="location-moves-title">
          <header className={styles.movesHead}>
            <h2 id="location-moves-title" className={styles.movesTitle}>
              Movimientos entre zonas
            </h2>
            <p className={styles.movesMeta}>Las últimas entradas y salidas detectadas. El registro completo está en Historial.</p>
          </header>
          {movesState.kind === "loading" && <Spinner label="Cargando movimientos…" />}
          {movesState.kind === "error" && <p className={styles.error}>No se pudieron cargar los movimientos.</p>}
          {movesState.kind === "loaded" && recentMoves.length === 0 && (
            <p className={styles.movesEmpty}>Todavía no se detectó ninguna entrada o salida de una geocerca.</p>
          )}
          {recentMoves.length > 0 && (
            <ol className={styles.moveList}>
              {recentMoves.map((move) => {
                const isEnter = move.event_type === "ENTER";
                const Icon = isEnter ? LogIn : LogOut;
                return (
                  <li key={move.id} className={styles.move}>
                    <time className={styles.moveTime} dateTime={move.occurred_at}>
                      {formatMoveTime(move.occurred_at)}
                    </time>
                    <span className={isEnter ? `${styles.moveIcon} ${styles.enter}` : styles.moveIcon}>
                      <Icon size={15} strokeWidth={2} aria-hidden="true" />
                    </span>
                    <span className={styles.moveText}>
                      <span className={styles.moveTitle}>{isEnter ? "Entrada a zona" : "Salida de zona"}</span>
                      <span className={styles.moveZone}>{move.geofence_name}</span>
                    </span>
                  </li>
                );
              })}
            </ol>
          )}
        </section>
      )}
    </>
  );
}
