"use client";

import { useCallback, useEffect, useState } from "react";

import { ApiError, type LocationReport, getLatestLocation } from "@/lib/apiClient";

type LocationState =
  | { kind: "loading" }
  | { kind: "loaded"; report: LocationReport | null }
  | { kind: "error"; message: string };

const GOOGLE_MAPS_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;

function describeError(error: unknown, fallback: string): string {
  return error instanceof ApiError ? error.message : fallback;
}

function formatCapturedAt(value: string): string {
  return new Date(value).toLocaleString("es-CO", { dateStyle: "medium", timeStyle: "short" });
}

/** Sprint 13. Renders a real embedded map only when NEXT_PUBLIC_GOOGLE_MAPS_API_KEY is
 * configured — that key can't be generated by an agent (it needs a Google Cloud account and an
 * HTTP-referrer restriction, same situation as GOOGLE_WEB_CLIENT_ID, see docs/sprint-13.md).
 * Without it, the panel still shows the coordinates as text plus a plain link to Google Maps
 * (which needs no API key), rather than hiding the feature entirely.
 */
export function DeviceLocationPanel({
  accessToken,
  deviceId,
}: {
  accessToken: string;
  deviceId: string;
}) {
  const [state, setState] = useState<LocationState>({ kind: "loading" });
  const [reloadToken, setReloadToken] = useState(0);

  // Same react-hooks/set-state-in-effect pattern as every other panel: setState only ever runs
  // inside a .then()/.catch() already chained in the effect body (see CLAUDE.md).
  useEffect(() => {
    let cancelled = false;

    getLatestLocation(accessToken, deviceId)
      .then(({ report }) => {
        if (!cancelled) {
          setState({ kind: "loaded", report });
        }
      })
      .catch((error) => {
        if (!cancelled) {
          setState({ kind: "error", message: describeError(error, "No se pudo cargar la ubicación") });
        }
      });

    return () => {
      cancelled = true;
    };
  }, [accessToken, deviceId, reloadToken]);

  const reload = useCallback(() => {
    setState({ kind: "loading" });
    setReloadToken((current) => current + 1);
  }, []);

  return (
    <div className="rulesPanel">
      <div className="devicesPanelHeader">
        <strong>Ubicación</strong>
        <button type="button" onClick={reload}>
          Actualizar
        </button>
      </div>

      {state.kind === "loading" && <p className="statusText">Cargando ubicación…</p>}
      {state.kind === "error" && <p className="authError">{state.message}</p>}

      {state.kind === "loaded" && state.report === null && (
        <p className="statusText">Todavía no hay ubicación reciente de este dispositivo.</p>
      )}

      {state.kind === "loaded" && state.report && (
        <div className="locationDetail">
          <p className="appMeta">
            Lat {state.report.latitude.toFixed(5)}, Lng {state.report.longitude.toFixed(5)}{" "}
            (±{Math.round(state.report.accuracy_meters)} m)
          </p>
          <p className="appMeta">Capturada: {formatCapturedAt(state.report.captured_at)}</p>

          {GOOGLE_MAPS_API_KEY ? (
            <iframe
              className="locationMap"
              title="Última ubicación conocida"
              width="100%"
              height="260"
              style={{ border: 0 }}
              loading="lazy"
              referrerPolicy="no-referrer-when-downgrade"
              src={`https://www.google.com/maps/embed/v1/view?key=${GOOGLE_MAPS_API_KEY}&center=${state.report.latitude},${state.report.longitude}&zoom=14`}
            />
          ) : (
            <>
              <p className="statusText">
                Configura NEXT_PUBLIC_GOOGLE_MAPS_API_KEY para ver el mapa embebido aquí (ver
                docs/sprint-13.md — requiere una clave de Google Cloud que un humano debe generar).
              </p>
              <a
                href={`https://www.google.com/maps?q=${state.report.latitude},${state.report.longitude}`}
                target="_blank"
                rel="noreferrer"
              >
                Abrir en Google Maps
              </a>
            </>
          )}
        </div>
      )}
    </div>
  );
}
