"use client";

import { ExternalLink, LocateFixed, MapPin, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { Button, Card, CardHeader, EmptyState, MetricCard, MetricGrid } from "@/components/ui";
import { ApiError, type LocationReport, getLatestLocation } from "@/lib/apiClient";

import styles from "./DeviceLocationPanel.module.css";

type LocationState =
  | { kind: "loading" }
  | { kind: "loaded"; report: LocationReport | null }
  | { kind: "error"; message: string };

const GOOGLE_MAPS_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;

function describeError(error: unknown, fallback: string): string {
  return error instanceof ApiError ? error.message : fallback;
}

function formatCapturedAt(value: string): string {
  return new Date(value).toLocaleString("es-CO", { dateStyle: "medium", timeStyle: "short" });
}

/** Sprint 13. Renders a real embedded map only when NEXT_PUBLIC_GOOGLE_MAPS_API_KEY is
 * configured — that key can't be generated by an agent (it needs a Google Cloud account and an
 * HTTP-referrer restriction, see docs/sprint-13.md). Without it, the panel still shows the
 * coordinates as text plus a plain link to Google Maps (which needs no API key).
 */
export function DeviceLocationPanel({
  accessToken,
  deviceId,
}: {
  accessToken: string;
  deviceId: string;
}) {
  const [state, setState] = useState<LocationState>({ kind: "loading" });
  const [reloadToken, setReloadToken] = useState(0);

  useEffect(() => {
    let cancelled = false;

    getLatestLocation(accessToken, deviceId)
      .then(({ report }) => {
        if (!cancelled) {
          setState({ kind: "loaded", report });
        }
      })
      .catch((error) => {
        if (!cancelled) {
          setState({ kind: "error", message: describeError(error, "No se pudo cargar la ubicación") });
        }
      });

    return () => {
      cancelled = true;
    };
  }, [accessToken, deviceId, reloadToken]);

  const reload = useCallback(() => {
    setState({ kind: "loading" });
    setReloadToken((current) => current + 1);
  }, []);

  const report = state.kind === "loaded" ? state.report : null;

  return (
    <>
      {report && (
        <MetricGrid>
          <MetricCard
            icon={LocateFixed}
            tone="info"
            label="Precisión aproximada"
            value={`±${Math.round(report.accuracy_meters)} m`}
          />
          <MetricCard
            icon={MapPin}
            tone="purple"
            label="Última captura"
            value={formatCapturedAt(report.captured_at)}
            hint="La ubicación se reporta cada ~15 minutos, no en tiempo real."
          />
        </MetricGrid>
      )}

      <Card padding="none">
        <div className={styles.head}>
          <CardHeader icon={MapPin} title="Última ubicación conocida" />
          <Button size="sm" icon={RefreshCw} onClick={reload} className={styles.refresh}>
            Actualizar
          </Button>
        </div>

        {state.kind === "loading" && (
          <div className={styles.body}>
            <p className={styles.hint}>Cargando ubicación…</p>
          </div>
        )}
        {state.kind === "error" && (
          <div className={styles.body}>
            <p className={styles.error}>{state.message}</p>
          </div>
        )}
        {state.kind === "loaded" && report === null && (
          <div className={styles.body}>
            <EmptyState icon={MapPin} title="Todavía no hay ubicación reciente de este dispositivo" />
          </div>
        )}

        {state.kind === "loaded" && report && (
          <div className={styles.body}>
            <p className={styles.coords}>
              Lat {report.latitude.toFixed(5)}, Lng {report.longitude.toFixed(5)}
            </p>

            {GOOGLE_MAPS_API_KEY ? (
              <iframe
                className={styles.map}
                title="Última ubicación conocida"
                loading="lazy"
                referrerPolicy="no-referrer-when-downgrade"
                src={`https://www.google.com/maps/embed/v1/view?key=${GOOGLE_MAPS_API_KEY}&center=${report.latitude},${report.longitude}&zoom=14`}
              />
            ) : (
              <div className={styles.noMap}>
                <p className={styles.hint}>
                  Configura <code>NEXT_PUBLIC_GOOGLE_MAPS_API_KEY</code> para ver el mapa embebido
                  aquí (requiere una clave de Google Cloud generada por una persona).
                </p>
                <a
                  className={styles.mapLink}
                  href={`https://www.google.com/maps?q=${report.latitude},${report.longitude}`}
                  target="_blank"
                  rel="noreferrer"
                >
                  Abrir en Google Maps <ExternalLink size={14} aria-hidden="true" />
                </a>
              </div>
            )}
          </div>
        )}
      </Card>
    </>
  );
}
