"""app rules: block/allow/daily-limit/schedule and rule enforcement events

Revision ID: 02c8782f69e6
Revises: fedd07a82d4e
Create Date: 2026-09-05 22:58:19.761162

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '02c8782f69e6'
down_revision: str | Sequence[str] | None = 'fedd07a82d4e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_rule_events',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type_applied', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("rule_type_applied IN ('ALLOW', 'BLOCK', 'DAILY_LIMIT', 'SCHEDULE')", name='ck_app_rule_events_type_valid'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_rule_events_device_id'), 'app_rule_events', ['device_id'], unique=False)
    op.create_table('app_rules',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('daily_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('schedule_start_minute', sa.Integer(), nullable=True),
    sa.Column('schedule_end_minute', sa.Integer(), nullable=True),
    sa.Column('schedule_days_mask', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(rule_type != 'DAILY_LIMIT') OR (daily_limit_minutes IS NOT NULL AND daily_limit_minutes > 0)", name='ck_app_rules_daily_limit_requires_minutes'),
    sa.CheckConstraint("(rule_type != 'SCHEDULE') OR (schedule_start_minute IS NOT NULL AND schedule_start_minute BETWEEN 0 AND 1439 AND schedule_end_minute IS NOT NULL AND schedule_end_minute BETWEEN 0 AND 1439 AND schedule_days_mask IS NOT NULL AND schedule_days_mask BETWEEN 1 AND 127)", name='ck_app_rules_schedule_requires_window'),
    sa.CheckConstraint("rule_type IN ('ALLOW', 'BLOCK', 'DAILY_LIMIT', 'SCHEDULE')", name='ck_app_rules_type_valid'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'package_name', name='uq_app_rules_device_package')
    )
    op.create_index(op.f('ix_app_rules_device_id'), 'app_rules', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_rules_device_id'), table_name='app_rules')
    op.drop_table('app_rules')
    op.drop_index(op.f('ix_app_rule_events_device_id'), table_name='app_rule_events')
    op.drop_table('app_rule_events')
    # ### end Alembic commands ###
