"""pairing: revoked_at and stable device instance id

Revision ID: 7dbb7e44e8b7
Revises: e27f40867c61
Create Date: 2026-09-04 09:04:44.163502

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7dbb7e44e8b7'
down_revision: str | Sequence[str] | None = 'e27f40867c61'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_instance_id', sa.String(length=64), nullable=True))
    op.create_index('uq_devices_instance_per_supervised_user', 'devices', ['supervised_user_id', 'device_instance_id'], unique=True, postgresql_where=sa.text('device_instance_id IS NOT NULL'))
    op.add_column('pairing_codes', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pairing_codes', 'revoked_at')
    op.drop_index('uq_devices_instance_per_supervised_user', table_name='devices', postgresql_where=sa.text('device_instance_id IS NOT NULL'))
    op.drop_column('devices', 'device_instance_id')
    # ### end Alembic commands ###
