"""categories: app category assignments and category rules

Revision ID: 9600bc530f75
Revises: bd93f41d0fa3
Create Date: 2026-09-07 03:25:16.394330

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9600bc530f75'
down_revision: str | Sequence[str] | None = 'bd93f41d0fa3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_category_assignments',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('SOCIAL_MEDIA', 'GAMES', 'STREAMING', 'EDUCATION', 'PRODUCTIVITY', 'COMMUNICATION', 'NEWS', 'SHOPPING', 'FINANCE', 'UTILITIES', 'ADULT_CONTENT')", name='ck_app_category_assignments_valid'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'package_name', name='uq_app_category_assignments_device_package')
    )
    op.create_index(op.f('ix_app_category_assignments_device_id'), 'app_category_assignments', ['device_id'], unique=False)
    op.create_table('category_rules',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('daily_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('schedule_start_minute', sa.Integer(), nullable=True),
    sa.Column('schedule_end_minute', sa.Integer(), nullable=True),
    sa.Column('schedule_days_mask', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(rule_type != 'DAILY_LIMIT') OR (daily_limit_minutes IS NOT NULL AND daily_limit_minutes > 0)", name='ck_category_rules_daily_limit_requires_minutes'),
    sa.CheckConstraint("(rule_type != 'SCHEDULE') OR (schedule_start_minute IS NOT NULL AND schedule_start_minute BETWEEN 0 AND 1439 AND schedule_end_minute IS NOT NULL AND schedule_end_minute BETWEEN 0 AND 1439 AND schedule_days_mask IS NOT NULL AND schedule_days_mask BETWEEN 1 AND 127)", name='ck_category_rules_schedule_requires_window'),
    sa.CheckConstraint("category IN ('SOCIAL_MEDIA', 'GAMES', 'STREAMING', 'EDUCATION', 'PRODUCTIVITY', 'COMMUNICATION', 'NEWS', 'SHOPPING', 'FINANCE', 'UTILITIES', 'ADULT_CONTENT')", name='ck_category_rules_category_valid'),
    sa.CheckConstraint("rule_type IN ('ALLOW', 'BLOCK', 'DAILY_LIMIT', 'SCHEDULE')", name='ck_category_rules_type_valid'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'category', name='uq_category_rules_device_category')
    )
    op.create_index(op.f('ix_category_rules_device_id'), 'category_rules', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_rules_device_id'), table_name='category_rules')
    op.drop_table('category_rules')
    op.drop_index(op.f('ix_app_category_assignments_device_id'), table_name='app_category_assignments')
    op.drop_table('app_category_assignments')
    # ### end Alembic commands ###
