"""device location reports: encrypted lat/lng insert-only history

Revision ID: ba8b839ae0eb
Revises: e4ff038efe89
Create Date: 2026-09-07 05:30:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ba8b839ae0eb'
down_revision: str | Sequence[str] | None = 'e4ff038efe89'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_location_reports',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('latitude_ciphertext', sa.Text(), nullable=False),
    sa.Column('longitude_ciphertext', sa.Text(), nullable=False),
    sa.Column('accuracy_meters', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('accuracy_meters >= 0', name='ck_device_location_reports_accuracy_valid'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_location_reports_device_id'), 'device_location_reports', ['device_id'], unique=False)
    op.create_index('ix_device_location_reports_device_captured', 'device_location_reports', ['device_id', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_location_reports_device_captured', table_name='device_location_reports')
    op.drop_index(op.f('ix_device_location_reports_device_id'), table_name='device_location_reports')
    op.drop_table('device_location_reports')
    # ### end Alembic commands ###
