"""device default app policy and DEFAULT_POLICY rule event type

Revision ID: bd93f41d0fa3
Revises: 02c8782f69e6
Create Date: 2026-09-05 21:05:00.000000

Written by hand rather than autogenerated: Alembic's autogenerate does not detect
CheckConstraint changes, and this revision has to rewrite one (app_rule_events gains the
DEFAULT_POLICY value). The column addition alone would have been autogenerated.

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd93f41d0fa3'
down_revision: str | Sequence[str] | None = '02c8782f69e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_EVENT_TYPES = "'ALLOW', 'BLOCK', 'DAILY_LIMIT', 'SCHEDULE'"
_NEW_EVENT_TYPES = "'ALLOW', 'BLOCK', 'DAILY_LIMIT', 'SCHEDULE', 'DEFAULT_POLICY'"


def upgrade() -> None:
    """Upgrade schema."""
    # server_default keeps every existing device on the pre-Sprint-9 behavior (blocklist mode),
    # so adding this column changes nothing about how anything already installed behaves.
    op.add_column(
        'devices',
        sa.Column(
            'default_app_policy',
            sa.String(length=16),
            nullable=False,
            server_default='ALLOW',
        ),
    )
    op.create_check_constraint(
        'ck_devices_default_policy_valid',
        'devices',
        "default_app_policy IN ('ALLOW', 'BLOCK')",
    )

    op.drop_constraint('ck_app_rule_events_type_valid', 'app_rule_events', type_='check')
    op.create_check_constraint(
        'ck_app_rule_events_type_valid',
        'app_rule_events',
        f"rule_type_applied IN ({_NEW_EVENT_TYPES})",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Rows recorded as DEFAULT_POLICY cannot satisfy the old constraint. Deleting them is the
    # only way back and is acceptable here: they are enforcement telemetry, not something other
    # tables reference, and a downgrade means the feature that produced them is being removed.
    op.execute("DELETE FROM app_rule_events WHERE rule_type_applied = 'DEFAULT_POLICY'")
    op.drop_constraint('ck_app_rule_events_type_valid', 'app_rule_events', type_='check')
    op.create_check_constraint(
        'ck_app_rule_events_type_valid',
        'app_rule_events',
        f"rule_type_applied IN ({_OLD_EVENT_TYPES})",
    )

    op.drop_constraint('ck_devices_default_policy_valid', 'devices', type_='check')
    op.drop_column('devices', 'default_app_policy')
