"""applications: device application catalog and daily usage

Revision ID: fedd07a82d4e
Revises: 7dbb7e44e8b7
Create Date: 2026-09-05 09:30:12.542362

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fedd07a82d4e'
down_revision: str | Sequence[str] | None = '7dbb7e44e8b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_application_usage',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('foreground_seconds', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'package_name', 'usage_date', name='uq_device_application_usage_day')
    )
    op.create_index(op.f('ix_device_application_usage_device_id'), 'device_application_usage', ['device_id'], unique=False)
    op.create_table('device_applications',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('app_label', sa.String(length=255), nullable=False),
    sa.Column('is_system_app', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uninstalled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'package_name', name='uq_device_applications_device_package')
    )
    op.create_index(op.f('ix_device_applications_device_id'), 'device_applications', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_applications_device_id'), table_name='device_applications')
    op.drop_table('device_applications')
    op.drop_index(op.f('ix_device_application_usage_device_id'), table_name='device_application_usage')
    op.drop_table('device_application_usage')
    # ### end Alembic commands ###
