import uuid

from pydantic import BaseModel, Field


class GoogleLoginRequest(BaseModel):
    # A Google ID token is a compact JWT; comfortably bounded well under this. Sprint 21: this
    # was the one input schema in the backend with no length limit at all before now.
    id_token: str = Field(min_length=1, max_length=4096)


class RefreshRequest(BaseModel):
    # Generated by generate_refresh_token() as secrets.token_urlsafe(48), ~64 characters.
    refresh_token: str = Field(min_length=1, max_length=512)


class LogoutRequest(BaseModel):
    refresh_token: str = Field(min_length=1, max_length=512)


class TokenPairResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"  # noqa: S105 -- the OAuth2 token_type field, not a secret
    expires_in: int


class CurrentUserResponse(BaseModel):
    id: uuid.UUID
    email: str
    display_name: str | None
    avatar_url: str | None
